// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: proto/query/campaigns.proto

package query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 캠페인 목록 조회 요청
type GetCampaignsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`   // 페이지 크기 (기본값: 10)
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // 오프셋 (기본값: 0)
	State         int32                  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`   // 캠페인 상태 필터 (옵션, 0=전체)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignsRequest) Reset() {
	*x = GetCampaignsRequest{}
	mi := &file_proto_query_campaigns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignsRequest) ProtoMessage() {}

func (x *GetCampaignsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_campaigns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignsRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignsRequest) Descriptor() ([]byte, []int) {
	return file_proto_query_campaigns_proto_rawDescGZIP(), []int{0}
}

func (x *GetCampaignsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCampaignsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetCampaignsRequest) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

// 캠페인 목록 조회 응답
type GetCampaignsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaigns     []*Campaign            `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignsResponse) Reset() {
	*x = GetCampaignsResponse{}
	mi := &file_proto_query_campaigns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignsResponse) ProtoMessage() {}

func (x *GetCampaignsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_campaigns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignsResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignsResponse) Descriptor() ([]byte, []int) {
	return file_proto_query_campaigns_proto_rawDescGZIP(), []int{1}
}

func (x *GetCampaignsResponse) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

func (x *GetCampaignsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// 특정 캠페인 조회 요청
type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    int64                  `protobuf:"varint,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_proto_query_campaigns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_campaigns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_proto_query_campaigns_proto_rawDescGZIP(), []int{2}
}

func (x *GetCampaignRequest) GetCampaignId() int64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

// 특정 캠페인 조회 응답
type GetCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *Campaign              `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignResponse) Reset() {
	*x = GetCampaignResponse{}
	mi := &file_proto_query_campaigns_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignResponse) ProtoMessage() {}

func (x *GetCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_campaigns_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignResponse) Descriptor() ([]byte, []int) {
	return file_proto_query_campaigns_proto_rawDescGZIP(), []int{3}
}

func (x *GetCampaignResponse) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

func (x *GetCampaignResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// 캠페인 데이터 구조
type Campaign struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // hex string으로 변환된 주소
	MerchantId     int64                  `protobuf:"varint,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MerchantName   string                 `protobuf:"bytes,4,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"` // JOIN으로 가져온 merchant 이름
	BasePrice      string                 `protobuf:"bytes,5,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`          // NUMERIC을 string으로 (정밀도 보장)
	MinQty         int64                  `protobuf:"varint,6,opt,name=min_qty,json=minQty,proto3" json:"min_qty,omitempty"`
	LockStart      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=lock_start,json=lockStart,proto3" json:"lock_start,omitempty"`
	LockEnd        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=lock_end,json=lockEnd,proto3" json:"lock_end,omitempty"`
	RmaxBps        int32                  `protobuf:"varint,9,opt,name=rmax_bps,json=rmaxBps,proto3" json:"rmax_bps,omitempty"`
	SavefloorBps   int32                  `protobuf:"varint,10,opt,name=savefloor_bps,json=savefloorBps,proto3" json:"savefloor_bps,omitempty"`
	MerchantFeeBps int32                  `protobuf:"varint,11,opt,name=merchant_fee_bps,json=merchantFeeBps,proto3" json:"merchant_fee_bps,omitempty"`
	OpsFeeBps      int32                  `protobuf:"varint,12,opt,name=ops_fee_bps,json=opsFeeBps,proto3" json:"ops_fee_bps,omitempty"`
	State          int32                  `protobuf:"varint,13,opt,name=state,proto3" json:"state,omitempty"`
	MetadataUri    string                 `protobuf:"bytes,14,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_proto_query_campaigns_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_campaigns_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_proto_query_campaigns_proto_rawDescGZIP(), []int{4}
}

func (x *Campaign) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Campaign) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Campaign) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *Campaign) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *Campaign) GetBasePrice() string {
	if x != nil {
		return x.BasePrice
	}
	return ""
}

func (x *Campaign) GetMinQty() int64 {
	if x != nil {
		return x.MinQty
	}
	return 0
}

func (x *Campaign) GetLockStart() *timestamppb.Timestamp {
	if x != nil {
		return x.LockStart
	}
	return nil
}

func (x *Campaign) GetLockEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.LockEnd
	}
	return nil
}

func (x *Campaign) GetRmaxBps() int32 {
	if x != nil {
		return x.RmaxBps
	}
	return 0
}

func (x *Campaign) GetSavefloorBps() int32 {
	if x != nil {
		return x.SavefloorBps
	}
	return 0
}

func (x *Campaign) GetMerchantFeeBps() int32 {
	if x != nil {
		return x.MerchantFeeBps
	}
	return 0
}

func (x *Campaign) GetOpsFeeBps() int32 {
	if x != nil {
		return x.OpsFeeBps
	}
	return 0
}

func (x *Campaign) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *Campaign) GetMetadataUri() string {
	if x != nil {
		return x.MetadataUri
	}
	return ""
}

func (x *Campaign) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_query_campaigns_proto protoreflect.FileDescriptor

const file_proto_query_campaigns_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/query/campaigns.proto\x12\x05query\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n" +
	"\x13GetCampaignsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x05R\x05state\"f\n" +
	"\x14GetCampaignsResponse\x12-\n" +
	"\tcampaigns\x18\x01 \x03(\v2\x0f.query.CampaignR\tcampaigns\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"5\n" +
	"\x12GetCampaignRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\x03R\n" +
	"campaignId\"X\n" +
	"\x13GetCampaignResponse\x12+\n" +
	"\bcampaign\x18\x01 \x01(\v2\x0f.query.CampaignR\bcampaign\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\xa2\x04\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\x03R\n" +
	"merchantId\x12#\n" +
	"\rmerchant_name\x18\x04 \x01(\tR\fmerchantName\x12\x1d\n" +
	"\n" +
	"base_price\x18\x05 \x01(\tR\tbasePrice\x12\x17\n" +
	"\amin_qty\x18\x06 \x01(\x03R\x06minQty\x129\n" +
	"\n" +
	"lock_start\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tlockStart\x125\n" +
	"\block_end\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\alockEnd\x12\x19\n" +
	"\brmax_bps\x18\t \x01(\x05R\armaxBps\x12#\n" +
	"\rsavefloor_bps\x18\n" +
	" \x01(\x05R\fsavefloorBps\x12(\n" +
	"\x10merchant_fee_bps\x18\v \x01(\x05R\x0emerchantFeeBps\x12\x1e\n" +
	"\vops_fee_bps\x18\f \x01(\x05R\topsFeeBps\x12\x14\n" +
	"\x05state\x18\r \x01(\x05R\x05state\x12!\n" +
	"\fmetadata_uri\x18\x0e \x01(\tR\vmetadataUri\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\x9d\x01\n" +
	"\fQueryService\x12G\n" +
	"\fGetCampaigns\x12\x1a.query.GetCampaignsRequest\x1a\x1b.query.GetCampaignsResponse\x12D\n" +
	"\vGetCampaign\x12\x19.query.GetCampaignRequest\x1a\x1a.query.GetCampaignResponseB\tZ\a./queryb\x06proto3"

var (
	file_proto_query_campaigns_proto_rawDescOnce sync.Once
	file_proto_query_campaigns_proto_rawDescData []byte
)

func file_proto_query_campaigns_proto_rawDescGZIP() []byte {
	file_proto_query_campaigns_proto_rawDescOnce.Do(func() {
		file_proto_query_campaigns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_query_campaigns_proto_rawDesc), len(file_proto_query_campaigns_proto_rawDesc)))
	})
	return file_proto_query_campaigns_proto_rawDescData
}

var file_proto_query_campaigns_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_query_campaigns_proto_goTypes = []any{
	(*GetCampaignsRequest)(nil),   // 0: query.GetCampaignsRequest
	(*GetCampaignsResponse)(nil),  // 1: query.GetCampaignsResponse
	(*GetCampaignRequest)(nil),    // 2: query.GetCampaignRequest
	(*GetCampaignResponse)(nil),   // 3: query.GetCampaignResponse
	(*Campaign)(nil),              // 4: query.Campaign
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_query_campaigns_proto_depIdxs = []int32{
	4, // 0: query.GetCampaignsResponse.campaigns:type_name -> query.Campaign
	4, // 1: query.GetCampaignResponse.campaign:type_name -> query.Campaign
	5, // 2: query.Campaign.lock_start:type_name -> google.protobuf.Timestamp
	5, // 3: query.Campaign.lock_end:type_name -> google.protobuf.Timestamp
	5, // 4: query.Campaign.created_at:type_name -> google.protobuf.Timestamp
	0, // 5: query.QueryService.GetCampaigns:input_type -> query.GetCampaignsRequest
	2, // 6: query.QueryService.GetCampaign:input_type -> query.GetCampaignRequest
	1, // 7: query.QueryService.GetCampaigns:output_type -> query.GetCampaignsResponse
	3, // 8: query.QueryService.GetCampaign:output_type -> query.GetCampaignResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_query_campaigns_proto_init() }
func file_proto_query_campaigns_proto_init() {
	if File_proto_query_campaigns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_query_campaigns_proto_rawDesc), len(file_proto_query_campaigns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_query_campaigns_proto_goTypes,
		DependencyIndexes: file_proto_query_campaigns_proto_depIdxs,
		MessageInfos:      file_proto_query_campaigns_proto_msgTypes,
	}.Build()
	File_proto_query_campaigns_proto = out.File
	file_proto_query_campaigns_proto_goTypes = nil
	file_proto_query_campaigns_proto_depIdxs = nil
}
